### ISSUE TITLE
CLion 2021.2.1中xmake建立新项目失败

### ISSUE THREAD

**Issue by hh-wu** [xmake-io/xmake-idea#12]
### 描述问题
CLion 2021.2.1中xmake建立新项目失败

### 错误信息
没有错误信息，直接卡住。看任务管理器。

将xmake进程结束后就不卡了，但是相关文件建立失败。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.8
- xmake运行平台：win10 home 20H2
- xmake目标平台：win10 home 20H2

### 其他信息

新建项目截图：
![image](https://user-images.githubusercontent.com/58615099/136652380-d22b6307-82b9-4aad-971a-3e7698a6f407.png)

卡住的截图
![image](https://user-images.githubusercontent.com/58615099/136652389-4d36f43b-a087-4c77-b90e-f95ea6fb0998.png)

任务管理器后台截图
![image](https://user-images.githubusercontent.com/58615099/136652406-597003a2-518c-4307-b1c8-7251302cc02f.png)

强制结束xmake进程后截图
![image](https://user-images.githubusercontent.com/58615099/136652521-6af8a1ee-bb8c-4824-9cdd-2496df74a11b.png)

**Comment by hh-wu** [comment]
手动执行命令没有问题，我想应该是xmake-idea的问题

**Comment by waruqi** [comment]
那你拉下代码 自己调下吧

**Comment by waruqi** [comment]
已经修复，不过刚提交新版本，正在等待审核，需要等到明天才能下载安装新版本

**Comment by hh-wu** [comment]
重新测试了一下，还是不行，无论idea还是clion，都无法正常生成文件。但是在gradle中runide模式下可以创建成功。

**Comment by waruqi** [comment]
看截图，不是工程成功创建了么。。没啥问题啊。。然后点 build 就行了。。

ide 那个 errors 是 deprecated api warnings 。。暂时不用管它，忽略就行了。。后面几天更新插件后 我还会去掉，但不影响现在使用

**Comment by hh-wu** [comment]
> 看截图，不是工程成功创建了么。。没啥问题啊。。然后点 build 就行了。。
> 
> ide 那个 errors 是 deprecated api warnings 。。暂时不用管它，忽略就行了。。后面几天更新插件后 我还会去掉，但不影响现在使用

不是的，这个是在xmake-idea中gradle开发环境下运行成功的。windows下Clion或者Idea+xmake-idea plugin运行失败。

**Comment by waruqi** [comment]
win上我也测过，可以的么。。那个 ide warning 1.1.6 应该也去掉了

**Comment by waruqi** [comment]
![Snip20211215_1](https://user-images.githubusercontent.com/151335/146159586-4124e6cc-e703-47d9-a36f-47be7525ce52.png)

我这里 win 上可以的么
