### ISSUE TITLE
Don't works in new CLion (error on the screenshot)

### ISSUE THREAD

**Issue by demidko** [xmake-io/xmake-idea#13]
<img width="621" alt="Screen Shot 2021-12-07 at 17 03 45" src="https://user-images.githubusercontent.com/26452002/144982315-c9a55a70-76ce-487d-b3ef-2e6b4d8217b2.png">

**Comment by waruqi** [comment]
I currently don’t have much time to maintain this plugin, you can modify plugin version range here

https://github.com/xmake-io/xmake-idea/blob/b3340ced4096e9eb111adf8f27d6496fbc66b097/gradle.properties#L4-L12

Then compile a local jar package and load it directly, and welcome to open a pr to help modify the version number

**Comment by waruqi** [comment]
I have uploaded the update, please wait for the official review time of one day
