### ISSUE TITLE
IDE Error - 

### ISSUE THREAD

**Issue by Frityet** [xmake-io/xmake-idea#15]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
Loading a XMake project produces an IDE error

### Expected behavior
No error should appear

### Error output

```yaml
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class io.xmake.run.XMakeRunConfigurationType$1'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: io.xmake]
```

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.8+202110281002,
- os: MacOS 10.15.7
- target platform: x86_64 Generic

**Comment by Frityet** [comment]
Note: the error gets spammed in the logs

**Comment by waruqi** [comment]
I have fixed it. v1.1.6
