### ISSUE TITLE
Not compatible with Clion 2022

### ISSUE THREAD

**Issue by taooceros** [xmake-io/xmake-idea#20]
### Xmake Version

2.6.5

### Operating System Version and Architecture

Windows 11 22H2, WSL

### Describe Bug

Not Compatible with newer Clion. 
![image](https://user-images.githubusercontent.com/45326534/166521952-e626f076-15e5-495d-b16e-4c10d69a3f01.png)

### Expected Behavior

Workable

**Comment by waruqi** [comment]
it works now.
