### ISSUE TITLE
Run Target does not support input

### ISSUE THREAD

**Issue by astrolemonade** [xmake-io/xmake-idea#26]
### Xmake Version

v2.7.5+202301262306

### Operating System Version and Architecture

Linux catalin 6.1.5-229.current #1 SMP PREEMPT_DYNAMIC Thu Jan 12 20:29:03 UTC 2023 x86_64 GNU/Linux

### Describe Bug

`Run Target` does not support input.
![image](https://user-images.githubusercontent.com/35623921/214978578-89301f6c-5d0b-4818-9311-6f2ccef00622.png)
I am trying to type but without success.
When I run the same command but in a terminal it works
![image](https://user-images.githubusercontent.com/35623921/214978690-9ce92a76-4eba-473c-91ab-e1f8b8602c6c.png)

### Expected Behavior

I should be able to input text directly in the xmake run target prompt or maybe run target could open a terminal instead and track that for changes.

### Project Configuration

```
add_rules("mode.debug", "mode.release")
set_languages("c99")
target("clox")
set_kind("binary")
add_includedirs("src")
add_files("src/*.c")
```

**Comment by waruqi** [comment]
edit run configuraion, you can set run arguments.

<img width="839" alt="image" src="https://github.com/user-attachments/assets/4c4ea4f5-a068-42f4-838d-b41f9446fe5f">
<img width="454" alt="image" src="https://github.com/user-attachments/assets/bd45ecad-5e9c-4139-b2e9-a92a4411dbfb">
