### ISSUE TITLE
无法在Clion 2020.1.1的插件商店中找到该插件

### ISSUE THREAD

**Issue by 45degree** [xmake-io/xmake-idea#3]
在Clion 2020.1.1的插件商店中没有xmake这个插件

**Comment by waruqi** [comment]
我看有的么 https://plugins.jetbrains.com/plugin/10156-xmake

**Comment by 45degree** [comment]
谢谢!

**Comment by zhylmzr** [comment]
目前最新的版本1.0.5只兼容到CLion 2019.3.6, 无法在2020.x.x版本运行

**Comment by waruqi** [comment]
这个暂时没办法 最近确实没太多时间更新 idea的插件搞起来比较折腾 现有源码都编译不过了

要支持新版本，得重新弄 等回头有时间再弄下 建议先用 xmake-vscode插件 支持更完善 还支持调试  定义跳转什么的，更新也比较及时
