### ISSUE TITLE
请求更新插件以兼容新版本CLion

### ISSUE THREAD

**Issue by TheWhiteDog9487** [xmake-io/xmake-idea#32]
### Xmake 版本

xmake v2.8.5+master.b5e571f97

### 操作系统版本和架构

Windows 11 家庭中文版 23H2 x64

### 描述问题

目前版本的XMake插件和最新的CLion不兼容。  
CLion版本：2023.3.1
![Snipaste_2023-12-21_16-37-49](https://github.com/xmake-io/xmake-idea/assets/60037547/b66f2195-a315-4568-9d2d-5910fb695caf)

### 期待的结果

更新插件版本以兼容新版本CLion

### 工程配置

/

### 附加信息和错误日志

/

**Comment by waruqi** [comment]
我不知道怎么更新兼容，已经把版本范围调到 29 年了，还是不行。。

https://github.com/xmake-io/xmake-idea/blob/4cf6d8bc621f3d41a51d0b9e18af99f4e4a9aeab/gradle.properties#L5

或者你们可以提个 pr 过来改进下。。

**Comment by TheWhiteDog9487** [comment]
> 我不知道怎么更新兼容，已经把版本范围调到 29 年了，还是不行，上传插件后，还是只到 23.3.2 结束。。
> 
> https://github.com/xmake-io/xmake-idea/blob/4cf6d8bc621f3d41a51d0b9e18af99f4e4a9aeab/gradle.properties#L5
> 
> 或者你们可以提个 pr 过来改进下。。

那这没办法了，只能先放这之后看看咋整。  
我如果能修那打开的就会是pr而不会是issue了（）

**Comment by TheWhiteDog9487** [comment]
诶不对啊
![Snipaste_2023-12-26_15-45-24](https://github.com/xmake-io/xmake-idea/assets/60037547/496419f5-f6c4-4d2f-a4f1-38b728591470)
![Snipaste_2023-12-26_15-45-39](https://github.com/xmake-io/xmake-idea/assets/60037547/a491db7c-f4e9-41ad-88ba-6ec9575d4f53)
为啥我这没问题？  
我就用JetBrains Toolbox更新过CLion的版本，然后更新了插件的版本，也把XMake从2.8.5更新到了2.8.6.  
这是啥情况？

**Comment by waruqi** [comment]
不是你反馈说不行么，我最近这两天，重新上传了一版。。

上面显示兼容范围还是到 23年 2 月。。没啥变化。。

<img width="605" alt="image" src="https://github.com/xmake-io/xmake-idea/assets/151335/8fbae3fa-7298-4be0-8a19-d7cd560a65fb">

**Comment by TheWhiteDog9487** [comment]
> 不是你反馈说不行么，我最近这两天，重新上传了一版。。
> 
> 上面显示兼容范围还是到 23年 2 月。。没啥变化。。
> <img alt="image" width="605" src="https://private-user-images.githubusercontent.com/151335/292836836-8fbae3fa-7298-4be0-8a19-d7cd560a65fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODUzNTksIm5iZiI6MTcwMzU4NTA1OSwicGF0aCI6Ii8xNTEzMzUvMjkyODM2ODM2LThmYmFlM2ZhLTcyOTgtNGJlMC04YTE5LWQ3Y2Q1NjBhNjVmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMDA0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmJmZjU5YWNkMjJhMTRhNzE1NGE5ZTMyOGZhZjMzMjIxMWNmNGRjZWZkYWJjNTdiMTExNTEzZjllNzIzYmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.umSlanXVfGcl67dJdqG-oWJzehsYdxks5k8X181Yv80">

重新看了下你的回复，抱歉抱歉我理解错了。  
我以为你的意思是你改过兼容版本之后没啥反应还是不能用。所以我这边更新完发现可以用之后又加了个回复。  
我的问题，抱歉。

**Comment by TheWhiteDog9487** [comment]
> 不是你反馈说不行么，我最近这两天，重新上传了一版。。
> 
> 上面显示兼容范围还是到 23年 2 月。。没啥变化。。
> <img alt="image" width="605" src="https://private-user-images.githubusercontent.com/151335/292836836-8fbae3fa-7298-4be0-8a19-d7cd560a65fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODUzNTksIm5iZiI6MTcwMzU4NTA1OSwicGF0aCI6Ii8xNTEzMzUvMjkyODM2ODM2LThmYmFlM2ZhLTcyOTgtNGJlMC04YTE5LWQ3Y2Q1NjBhNjVmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMDA0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmJmZjU5YWNkMjJhMTRhNzE1NGE5ZTMyOGZhZjMzMjIxMWNmNGRjZWZkYWJjNTdiMTExNTEzZjllNzIzYmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.umSlanXVfGcl67dJdqG-oWJzehsYdxks5k8X181Yv80">

感谢您这几天的折腾，谢谢！
