### ISSUE TITLE
插件市场里好像无法搜到xmake-idea插件了

### ISSUE THREAD

**Issue by ZacharyJia** [xmake-io/xmake-idea#4]
### 描述讨论详情
插件市场里好像无法搜到xmake-idea插件了，作者是否能够重新更新上架一下插件呢？

**Comment by waruqi** [comment]
这个没办法，idea的插件就是比较坑，时间长了 会自动出现各种不兼容问题，需要强推你升级插件代码，而且之前的插件代码 都会编译不过，又要重新捣鼓一遍开发环境，还得重新研究 idea 里面各种新版本的定制支持。

这比较花时间，我暂时没精力更新了，等之后有时间的时候 我会考虑的。

你可以考虑先用 xmake-vscode的插件，更新比较及时，兼容性和体验都是最好的，还支持调试，有问题 我也会及时处理。

**Comment by waruqi** [comment]
这个插件已经更新支持 idea/clion 2021，并且已经重新发布

https://plugins.jetbrains.com/plugin/17406-xmake
