### ISSUE TITLE
macOS 需要手动添加配置并且没有调试模式

### ISSUE THREAD

**Issue by L-Super** [xmake-io/xmake-idea#44]
### Xmake 版本

v2.9.3+20240624

### 操作系统版本和架构

macOS 14.4.1 

### 描述问题

在CLion上，安装xmake插件后，无法直接打开xmake工程，打开`xmake.lua`只是打开该文件。
新建工程，未自动创建配置。可以build，但是run会报错：
```
Please select a xmake run configuration first!
```
需要手动添加配置。

还有就是，调试模式置灰，不可用状态。

### 期待的结果

能够打开工程，新建工程能自动配置，启用调试模式

### 工程配置

```xmake
add_rules("mode.debug", "mode.release")

target("xmake-demo")
    set_kind("binary")
    add_files("src/*.cpp")
```

### 附加信息和错误日志

```
/opt/homebrew/bin/xmake -y
[100%]: build ok, spent 0.126s

进程已结束，退出代码为 0
Please select a xmake run configuration first!
```

**Comment by waruqi** [comment]
run 你需要自己创建个 配置。

**Comment by L-Super** [comment]
不能想cmake一下，自动创建配置吗

**Comment by waruqi** [comment]
你可以来个 pr 支持上

**Comment by L-Super** [comment]
那调试器为什么不能使用呢？也需要额外配置？

**Comment by waruqi** [comment]
> 那调试器为什么不能使用呢？也需要额外配置？

暂时不支持，实现复杂度和时间成本太高。你也可以提个 pr 过来。

**Comment by windchargerj** [comment]
Creating a new **_XMake_** project will now automatically add a `run` configuration. #49

Unfortunately, an automatic `build` task before `run` still needs to wait for the completion of code refactoring.

**Comment by waruqi** [comment]
> Unfortunately, an automatic build task before run still needs to wait for the completion of code refactoring.

`set_policy("run.autobuild", true)` or `xmake f --policies=run.autobuild`

**Comment by waruqi** [comment]
> > Unfortunately, an automatic build task before run still needs to wait for the completion of code refactoring.
> 
> `set_policy("run.autobuild", true)` or `xmake f --policies=run.autobuild`

we can add `--policies=run.autobuild` as a default additional config argument in run configuraion.

**Comment by waruqi** [comment]
自动构建运行加上，等待几天后的新版本。
