### ISSUE TITLE
Use a new abstraction to run xmake utility

### ISSUE THREAD

**Issue by windchargerj** [xmake-io/xmake-idea#46]
### Is your feature request related to a problem? Please describe.

XMake currently operates only locally. While it supports remote compilation, it still requires a local XMake client. Utilizing remote XMake binaries at the IDE plugin level offers significant benefits. However, the existing SDK model in XMake is complex to extend on the IntelliJ platform, which is designed for JDK-like toolkits. I recommend developing a customized XMake toolkit model to enable a cross-platform experience when running XMake binaries.

### Describe the solution you'd like

For the new XMake model, I plan to enhance at lease the following features at lease:

- **Automatic detection of XMake programs across WSL and remote environments**:
XMake is accessible via the system path in WSL and SSH environments. Note that the SSH feature is exclusive to the commercial version, so functionality may vary across different IDEs.

![image](https://github.com/user-attachments/assets/c02018a4-8a23-45e2-a61c-69cadbe11ab6)

- **Configurable selection of XMake programs for different platforms**:
Each configuration file can specify an XMake program tailored for cross-platform development.

![image](https://github.com/user-attachments/assets/9c45c5c6-0c88-4973-ba4a-c1f9db44fb1c)

- **Synchronization of source code and generated files for remote builds and execution**:
Capturing output from remote builds and example programs executed in the remote environment.

_Build:_

![image](https://github.com/user-attachments/assets/27d63dd0-483f-4737-b535-9832d9b490c2)

_Run:_

![image](https://github.com/user-attachments/assets/f2499a24-f19e-40a4-9c1a-9a145248f178)

### Describe alternatives you've considered

Overview of All Planned Enchancements:
- [x] XMake Toolkit Model
- [x] XMake Toolkit Detect and Manage Service
- [x] XMake Toolkit Select ComboBox
- [x] XMake Toolkit Process Run
- [x] XMake Toolkit State Storage
- [x] XMake Target Detect and Manage Service
- [x] XMake Registered Tookit Management
- [x] Configurable Adaption
- [x] Working Directory Select Browser
- [x] RunConfiguration Adaption
- [x] Configurable Adaption
- [x] Essential Change in New Project Wizard
- [x] Basic Project Sync (Recommand to use Rsync)

### Additional context

Issues that could potentially be addressed:
- Run and build on wsl and  remote:
#18
- Basic muliconfiguration support:
#28

**Comment by waruqi** [comment]
Thanks, I have uploaded new version to markket.
