### ISSUE TITLE
It seems that xmake plug-in is not support on idea collection 2020

### ISSUE THREAD

**Issue by juteman** [xmake-io/xmake-idea#5]
Well, I use vscode only for some script. For c++ project, I would like to use to clion or visual stduio more.

Although I don't know how to write kotlin, but I know how to write java or c#. So I think I can pay some time on xmake plug-in in idea.

**Comment by waruqi** [comment]
Yes, after the version of idea is upgraded, it is no longer compatible with xmake-idea plugin.

The plug-in code of xmake-idea is also completely incompatible with the new idea plug-in development environment, so I may take a lot of time to improve it to support the new version of idea.

Sorry, although I really want to support the new idea IDE, I don’t have much time to improve it at the moment. I suggest you use the xmake-vscode plugin, it provides more functions and is easier to use.

**Comment by juteman** [comment]
## Development Log:
2020/12/4

https://github.com/juteman/xmake-idea/commit/cb419091e2f1c9ba2a7a582132a1906d63a7c2ec

log:
+ change environment to gradle. which is recommend by 
+ change the resource structure
+ change the source code structure and package structure
+ fix Syntax Error in XMakeToolWindowOutputPanel.kt
+ fix Syntax Error in XMakeToolWindowProblemPanel.kt

---

lots of things need to be done.

**Comment by juteman** [comment]
I will create all into a pull request after I test it could run on clion 2020.

**Comment by waruqi** [comment]
Oh, it's great, Thank you very much. :simle:

**Comment by juteman** [comment]
This is the run configuration code like:

```kotlin
    override fun createEditor(): JComponent = panel {

        labeledRow("Default target:", targetsComboBox) {
            targetsComboBox(CCFlags.push)
        }

        labeledRow("Run arguments:", runArguments) {
            runArguments.apply {
                dialogCaption = "Run arguments"
                makeWide()
            }()
        }
        row(environmentVariables.label) { environmentVariables.apply { makeWide() }() }
    }
```

This is the picture in README

![](https://raw.githubusercontent.com/tboox/xmake-idea/master/res/run_configuration.png)

So, What about the text label with "Environment Variables" ?
And Where is the label  "Run arguments"?

And I almost rewrite this code part  and get this result
![2020-12-10_16-18-32](https://user-images.githubusercontent.com/13850064/101740471-d3d7ad80-3b03-11eb-8176-757008792b2f.png)

**Comment by waruqi** [comment]
> So, What about the text label with "Environment Variables" ?
And Where is the label "Run arguments"?

Oh, I'm sorry, I can't remember where it is because of the long time. Maybe you can only look at the code to find the location. : (

**Comment by juteman** [comment]
> > So, What about the text label with "Environment Variables" ?
> > And Where is the label "Run arguments"?
> 
> Oh, I'm sorry, I can't remember where it is because of the long time. Maybe you can only look at the code to find the location.
> : (

I think there miss "Run arguments"  label before refer to the code.

**Comment by waruqi** [comment]
> I think there miss "Run arguments" label before refer to the code.

I seem to remember that it was placed on a global project configuration panel, but it was not placed on the run configuration panel.

**Comment by juteman** [comment]
I am now busy for Q4 deadline, so I have no time  on this project for one or two weeks. And some of the partial can work now.


---


 But I found some features maybe missing in this project. For example, C/C++ project with XMake can't supported by clangd and clang-tidy which integrated by clion, so it can't not get right semantic coloring of C/C++ and smart completions or symbol jumping. This problem also appear on xmake script，lua plugin can't give any support for xmake script. Other like xmake profile and xmake coverage should also be integrated. 

The ideal situation would be to make a project like [bazelbuild/intellij](https://github.com/bazelbuild/intellij) , but a project like that needed much work to do.

**Comment by waruqi** [comment]
Yes, this requires a lot of work, and I don't have time to improve it too, so you can also try the xmake-vscode plugin.

**Comment by skitsanos** [comment]
Is there any way to have xmake plugin working for Clion 2020 at least?

**Comment by waruqi** [comment]
There is currently no way, I will consider rewriting the new version of the plugin in the future. But it may take some time to wait.

**Comment by juteman** [comment]
I've got some time now. And I consider to make a plugin like [bazelbuild-plugin](https://github.com/bazelbuild/intellij), But I have recently become addicted to 'Street Fighter V'. Anyway, I will take the time to investigate this programme.

**Comment by waruqi** [comment]
xmake-idea has been updated to support the latest idea/clion 2021, and has been re-released to the market.

https://plugins.jetbrains.com/plugin/17406-xmake
