### ISSUE TITLE
无法检测到  xmake 工具链 并且还不允许选择路径 

### ISSUE THREAD

**Issue by Super1Windcloud** [xmake-io/xmake-idea#57]
### Xmake Version

latest

### Operating System Version and Architecture

win11 

### Describe Bug

![image](https://github.com/user-attachments/assets/90283c3f-6484-47dd-b38c-65b8f54e8a2c)

### Expected Behavior

通过 scoop  install xmake,  你的插件无法找到路径, 

### Project Configuration

.

### Additional Information and Error Logs

..

**Comment by waruqi** [comment]
@windchargerj any idea?

**Comment by windchargerj** [comment]
Check if the **_XMake_** binary can be found using `where.exe`. If not, try adding it to the **PATH** manually. The functionality for manually managing multiple versions of **_XMake_** is mostly developed, but I haven't had time in the next two months to refine it to a mergeable state. However, I expect to be able to submit it by January next year.

**Comment by Super1Windcloud** [comment]
很简单, 你只需在 configurationType 添加一个选择路径的框框就行了, 或者在 path中检测中添加个分支 到 $Scoop\xmake\current\路径检测

**Comment by windchargerj** [comment]
In my setup, **_XMake_** installed via **_Scoop_** is automatically detectable. Adding the **_Scoop_** **_XMake_** installation directory to the system `PATH` should assist the plugin in finding **_XMake_**.

![屏幕截图 2024-10-23 194404](https://github.com/user-attachments/assets/ce26e9f0-87ea-4d78-98fe-3fc0d6cb5769)

This plugin uses `where.exe` on _Windows_ to detect **_XMake_**. You can use the `where.exe` command to check if it can be found.

![屏幕截图 2024-10-23 204731](https://github.com/user-attachments/assets/e3b9fee5-60a1-48e3-9488-1b24b8fa9c3e)

If problems persist, consider adding the directory to `io/xmake/utils/execute/Instruction.kt` to see if it resolves the issue.

```
val predefinedPath = mapOf(
    "windows" to arrayOf(),
    "unix" to arrayOf(
        // Todo: Add more paths
        "\${HOME}/.local/bin",
        "/usr/local/bin",
        "/usr/bin",
        "/opt/homebrew/bin",
    )
)
```

**Comment by Super1Windcloud** [comment]
我呈现的画面不太一样诶, 是不是插件不支持clion2024.2

**Comment by Super1Windcloud** [comment]
![image](https://github.com/user-attachments/assets/a093b92f-6dd6-432c-b8f5-149b94ac1e4e)
Xmake路径在path中

**Comment by Super1Windcloud** [comment]
属实无语, 原来是延迟的问题, 等了好几秒才能检测到
